name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install server deps
        run: |
          cd server
          npm install
      - name: Run tests
        run: |
          cd server
          npm test
